branches:
  - main
repositoryUrl: https://github.com/dsmdavid/boilerplate-container-action
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"